### PR TITLE
New attribute atkckeditorattribute

### PR DESCRIPTION
**Pull request by wayneh**
Uses CKEditor v4.4.0 April 2014
Functional replacement for atkhtmlattribute which uses FCK editor - the
predecessor to CKEditor

### CODE REVIEW

**Comment by PhrozenByte** [comment]
- What do you think about really replacing `atkfckattribute` (= `atkfckattribute extends atkckeditorattribute` + document `atkfckattribute` as `@deprecated`)?
- Can you please add some options to configure CKEditor (like `atkfckattribute`)?
- Can you please apply FIG PSR-2 to the PHP class?

**Comment by wayneh** [comment]
Subject: Re: [atk] New attribute atkckeditorattribute (#10)
-   What do you think about really replacing atkfckattribute (= atkfckattribute extends atkckeditorattribute + document atkfckattribute as @deprecated)?

[WH] Could do this but what about probable incompatibility between the toolbar options in each and Users needing to change ?
-   Can you please add some options to configure CKEditor (like atkfckattribute)?

[WH] Good idea - done
-   Can you please apply FIG PSR-2 to the PHP class?

[WH] Under windows or online is there any tool to do this ?

Am using NetBeans but there doesn’t seem to be a plugin/setting for this

How to I “replace” the pull request with the new stuff ?

Thanks

W

**Comment by dalers** [comment]
> On Apr 30, 2014, at 11:14 PM, Wayne notifications@github.com wrote:
> 
> Subject: Re: [atk] New attribute atkckeditorattribute (#10) 
> - What do you think about really replacing atkfckattribute (= atkfckattribute extends atkckeditorattribute + document atkfckattribute as @deprecated)? 
> 
> [WH] Could do this but what about probable incompatibility between the toolbar options in each and Users needing to change ? 
> - Can you please add some options to configure CKEditor (like atkfckattribute)? 
> 
> [WH] Good idea - done 
> - Can you please apply FIG PSR-2 to the PHP class? 
> 
> [WH] Under windows or online is there any tool to do this ? 
> 
> Am using NetBeans but there doesn’t seem to be a plugin/setting for this 

I think David said he used NetBeans, I'm hoping he can explain exactly how.

**Comment by PhrozenByte** [comment]
> Could do this but what about probable incompatibility between the toolbar options in each and Users needing to change?

Good point! That's a question about downward compatibility. I tend to replace the editor and accept the maybe emerging problems. Personally, I think that we should update all of our 3rd party applications and frameworks, they propably solve major bugs. As you said: CKEditor is FCKeditor - just in a much newer version.

> Am using NetBeans but there doesn’t seem to be a plugin/setting for this

You can use code formatting under Tools -> Options -> Editor -> Formatting -> Language: PHP. I'm afraid I can't export my options, you must configure it on your own. When everyhting is set up, you can use Source -> Format within a single file or a directory selected. For new development and for small files like `class.atkckeditor.inc`, you can do this manually as well. Please note that our code styling doesn't apply to 3rd party code - so don't change CKEditor itself, just `class.atkckeditor.inc`.

> How to I “replace” the pull request with the new stuff ?

To add new changes simply pull to the branch again. As I can see you usually use your `develop` branch, so simply change things locally and push to GitHub. If you want to work on multiple projects at a time, create multiple branches locally and switch between them - when work is finished, push the branch to GitHub and open a pull request. I usally use branches like `feature/someNewFeature` or `fix/someBugFixed`. You can, but mustn't use `develop` :smiley:

> I think David said he used NetBeans, I'm hoping he can explain exactly how.

Daniel :smile:

**Pull request closed without merging**
