### PR TITLE
issue #7: ATK winxp theme error in PHP: 5.3.8 and higher fixed

### PR DESCRIPTION
**Pull request by wayneh**
patch to apply: ATK winxp theme error in PHP: 5.3.8 and higher
(Deprecated functions) #7

### CODE REVIEW

**Comment by PhrozenByte** [comment]
Never merge into `master`, merge into `develop` only. I've resetted the commits.

**Comment by wayneh** [comment]
Sorry Daniel – my inexperience – didn’t pay enough attention to the branch !

Thanks for fixing

W

**Comment by PhrozenByte** [comment]
no problem ;)
Some days ago, I've merged a change of klaaspeter into Achievo fixing some PHP error (without further validation). Unfortunately, his change caused an redirection loop. I've fixed that today, but thought about an simple method to let another developer look over the changes. What do you think about mutual checks? We don't merge changes on our own, but merge changes of another. Concrete: I accept and merge your pull requests, and you accept and merge my pull requests. What do you think?

**Comment by wayneh** [comment]
Yes happy with that but only for ATK – I have never installed/used Achievo so not rally any point me looking at that :)

Regards

Wayne

**Comment by dalers** [comment]
That's great about the redirect fix. I'll continue with php 5.4 until the next issue. Regarding peer review, I agree in principle, but fear I won't be adding value other than testing. I'll look at the commit you reverted/modified to fix the issue and see if I would have caught the redirect bug.

I'm switching from XAMPP to wamp (on windows) so I can easily switch between php versions. Back in commission tonight.

Is klaaspeter active? I haven't heard from him in some time.

Dale

**Comment by klaaspeter** [comment]
Dale,

I used klaaspeter account just for ATK and Achievo, I add just right now my other account to the ATK team, I will be helping again if that is ok :).

So if I can do anything just let me know :)

**Pull request merged**
